# Config File
Lobbies:
  Lobby:
    Spawn:
      World: world
      X: -599.5
      Y: 16
      Z: -198.5
      Yaw: 0
      Pitch: 0
    Signs:
      RankUpLobby:
        Sign:
          World: world
          X: -600
          Y: 18
          Z: -181
          Line1: ''
          Line2: 'Warp to:'
          Line3: '&9Rank Up Lobby'
          Line4: ''
        Spawn:
          World: world
          X: -681.5
          Y: 4
          Z: -217.5
          Yaw: 0
          Pitch: 0
  RankUpLobby:
    Spawn:
      World: world
      X: -681.5
      Y: 4
      Z: -217.5
      Yaw: 0
      Pitch: 0
    Signs:
      I:
        World: world
        X: -678
        Y: 6
        Z: -211
      II:
        World: world
        X: -686
        Y: 6
        Z: -211
#      III:
#        World:
#        X:
#        Y:
#        Z:
#      IV:
#        World:
#        X:
#        Y:
#        Z:
#      V:
#        World:
#        X:
#        Y:
#        Z:
#      VI:
#        World:
#        X:
#        Y:
#        Z:
#      VII:
#        World:
#        X:
#        Y:
#        Z:
#      VIII:
#        World:
#        X:
#        Y:
#        Z:
#      IX:
#        World:
#        X:
#        Y:
#        Z:
#      X:
#        World:
#        X:
#        Y:
#        Z:

Ranks:
  I:
    Spawn:
      World: world
      X: -551.5
      Y: 2
      Z: -89.5
      Yaw: 25
      Pitch: 0
    Sign:
      World: world
      X: -554
      Y: 25
      Z: -44
  II:
    Spawn:
      World: world
      X: -652.5
      Y: 8
      Z: -60.5
      Yaw: -160
      Pitch: 0
    Sign:
      World: world
      X: -642
      Y: 22
      Z: -39
  III:
    Spawn:
      World: world
      X: -770.5
      Y: 3
      Z: -44.5
      Yaw: 145
      Pitch: 0
    Sign:
      World: world
      X: -758
      Y: 27
      Z: -50
#  IV:
#    Spawn:
#      World:
#      X:
#      Y:
#      Z:
#      Yaw:
#      Pitch:
#    Sign:
#      World:
#      X:
#      Y:
#      Z:
#  V:
#    Spawn:
#      World:
#      X:
#      Y:
#      Z:
#      Yaw:
#      Pitch:
#    Sign:
#      World:
#      X:
#      Y:
#      Z:
#  VI:
#    Spawn:
#      World:
#      X:
#      Y:
#      Z:
#      Yaw:
#      Pitch:
#    Sign:
#      World:
#      X:
#      Y:
#      Z:
#  VII:
#    Spawn:
#      World:
#      X:
#      Y:
#      Z:
#      Yaw:
#      Pitch:
#    Sign:
#      World:
#      X:
#      Y:
#      Z:
#  VIII:
#    Spawn:
#      World:
#      X:
#      Y:
#      Z:
#      Yaw:
#      Pitch:
#    Sign:
#      World:
#      X:
#      Y:
#      Z:
#  IX:
#    Spawn:
#      World:
#      X:
#      Y:
#      Z:
#      Yaw:
#      Pitch:
#    Sign:
#      World:
#      X:
#      Y:
#      Z:
#  X:
#    Spawn:
#      World:
#      X:
#      Y:
#      Z:
#      Yaw:
#      Pitch:
#    Sign:
#      World:
#      X:
#      Y:
#      Z:
